version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: specs_postgres
    environment:
      POSTGRES_DB: specs_auth
      POSTGRES_USER: specs_user
      POSTGRES_PASSWORD: specs_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U specs_user -d specs_auth"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
